### ISSUE TITLE
sunburst demo flashing in browser

### ISSUE THREAD

**Issue by MarioClaerhout** [PatMartin/dexjs#1]
Your demo : https://bl.ocks.org/PatMartin/2b3d11ad2eef3c57f9b9561cda7e64bd seams to contain some bug.  I've tried it in several browsers : the screen starts flashing, as if the program is in some eternal loop.

**Comment by PatMartin** [comment]
Painful, but fixed.  Bad interaction with an iframe caused shrinkage.  Set minimum boundaries and also encountered a second bug in my cross browser testing related to text auto-sizing.
