### ISSUE TITLE
TreeMap demo doesn't work in IE

### ISSUE THREAD

**Issue by MarioClaerhout** [PatMartin/dexjs#2]
I've tried your Treemap demo in several browsers : https://bl.ocks.org/PatMartin/112191b94399a5e4172c7d2621b31df5
It works perfectly fine.  Unfortunately the names of the states aren't correctly displayed in Internet Explorer (11).

**Comment by PatMartin** [comment]
At first I was going to scratch this up to IE's poor adherence to the HTML5 specification, but I tested this in FIrefox and the bug exists there too.

Thanks for the heads up on this!  I will be sure to look into it.

**Comment by PatMartin** [comment]
Fixed.  Firefox and IE do not implement baseline-alignment=hanging the same as Chrome.  So I switched it out for a dy offset of .8em and it works across browsers now.

Thanks for the bug report!
